modLoader="javafml"
loaderVersion="${forge_loader_range}"
license="MIT"
issueTrackerURL="https://github.com/TonimatasDEV/Architectury/issues"

[[mods]]
modId="example"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="http://myurl.me/"
displayURL="https://tonimatas.dev"
logoFile="icon.png"
#credits="Thanks for this example mod goes to Java"
authors="TonimatasDEV"
#displayTest="MATCH_VERSION"

description='''
Example for create mods on Architectury
'''

[[dependencies.example]]
   modId="forge"
   mandatory=true
   versionRange="${forge_loader_range}"
   ordering="NONE"
   side="BOTH"
[[dependencies.example]]
   modId="minecraft"
   mandatory=true
   versionRange="${forge_minecraft_version_range}"
   ordering="NONE"
   side="BOTH"
