modLoader="javafml"
loaderVersion="${neoforgeLoaderRange}"
license="MIT"
issueTrackerURL="${modIssueTracker}"

[[mixins]]
config="example-common.mixins.json"

[[mixins]]
config="example-neoforge.mixins.json"

[[mods]]
modId="example"
version="${modVersion}"
displayName="${modName}"
#updateJSONURL="http://myurl.me/"
displayURL="https://example.example"
#logoFile="icon.png"
#credits="Thanks for this example mod goes to Java"
authors="${modAuthor}"
#displayTest="MATCH_VERSION"

description='''
${modDescription}
'''

[[dependencies.example]]
   modId="neoforge"
   mandatory=true
   versionRange="${neoforgeLoaderRange}"
   ordering="NONE"
   side="BOTH"

[[dependencies.example]]
   modId="minecraft"
   mandatory=true
   versionRange="${neoforgeMinecraftVersionRange}"
   ordering="NONE"
   side="BOTH"